services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    restart: always
    container_name: newbee
    init: true
    deploy:
      resources:
        limits:
          cpus: "1.00"  # 최대 1개의 코어 할당
          memory: 2GB   # 최대 2GB의 메모리 할당